### ISSUE TITLE
Issues building on Windows VS 2017

### ISSUE THREAD

**Issue by gquipster** [sbrown89/libzbar#1]
**Describe the bug**
Following instructions on README.MD fails to build - fails on link stage with error:

LINK : warning LNK4044: unrecognized option '/install_name'; ignored [D:\Dev\libzbar-libzbar-0.11.2\build\zbar\libzbar.vcxproj]
LINK : warning LNK4044: unrecognized option '/lSystem'; ignored [D:\Dev\libzbar-libzbar-0.11.2\build\zbar\libzbar.vcxproj]
LINK : warning LNK4044: unrecognized option '/compatibility_version'; ignored [D:\Dev\libzbar-libzbar-0.11.2\build\zbar\libzbar.vcxproj]
LINK : warning LNK4044: unrecognized option '/current_version'; ignored [D:\Dev\libzbar-libzbar-0.11.2\build\zbar\libzbar.vcxproj]
LINK : fatal error LNK1181: cannot open input file '@executable_path\Frameworks\liblibzbar.dylib' [D:\Dev\libzbar-libzbar-0.11.2\build\zbar\libzbar.vcxproj]

**To Reproduce**
1. Downloaded ZIP file release of 0.11.2 and unzipped to folder
2. Made build directory and changed to it
3. Issued command: >cmake -A x64 "-DCMAKE_INSTALL_PREFIX=C:/lib/libzbar" "-DCMAKE_BUILD_TYPE=Release" ..
4. Issued command: >cmake --build . --config Release --target INSTALL  
5. See error

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 build 1903
 - Visual Studio 2017 Pro version 15.9.14

Hoping to use the resulting library to create Windows version of the zbarimg program to parse barcodes out of PDF files

**Comment by sbrown89** [comment]
Did you use the visual studio developer command prompt? The standard windows terminal will not work.

**Comment by gquipster** [comment]
Yes, used the developer command prompt

**Comment by sbrown89** [comment]
I was able to reproduce the bug, was caused by the fix I put in-place for IOS linking. This is now fixed and a new release has been published. libzbar-0.11.3. Thanks for reporting this.

**Comment by gquipster** [comment]
Confirmed now compiles
